version: '3'
services:
  nginx:
    container_name: nginx
    links:
      - app
    ports:
      - 80:80
      - 443:443
    build: ./nginx

  app:
    container_name: app
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    links:
      - mongodb
      - rabbitmq
    command: mvn clean spring-boot:run

  authentication:
    container_name: authentication
    build: ./authentication
    working_dir: /authentication
    volumes:
      - ./authentication:/authentication
    links:
      - db
    command: mvn clean spring-boot:run

  db:
    container_name: mysql
    image: library/mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=products
    expose:
      - '27017'

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    restart: "no"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    labels:
      NAME: "rabbitmq1"
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    container_name: consumer
    build: ./consumer
    working_dir: /consumer
    volumes:
      - ./consumer:/consumer
    links:
      - rabbitmq
    command: mvn clean spring-boot:run